### ISSUE TITLE
"Too many words in one hypothesis" Error

### ISSUE THREAD

**Issue by turchmo** [rousseau-lium/XenC#2]
Dear All,
I'm running XenC in mode 2 using a large quantity of out-domain data and a small quantity of in-domain data. 
It works fine till a certain step, then it emits "Too many words in one hypothesis" and crashes. Do you have suggestion on how to solve this problem?

Thanks a lot!

**Comment by loicbarrault** [comment]
Hi,

this is due to a constant specifying the maximum length for a sentence. And it seems that your corpus contains one or several very big sentences.

Check the constant MAX_WORDS in XenLMsri.h. Try to increase it.

But maybe your corpus is not clean, and you might want to remove (or split) those very long sentences.

Good luck.
Best regards.
Loïc

**Comment by turchmo** [comment]
Hi Loïc,
you are right, my corpus was not clean. I'll check, but probably there are very long sentence!

Thanks a lot for your help!
Marco

**Comment by antho-rousseau** [comment]
Hi Marco,

as Loïc already stated, cleaning your corpus or fiddling with the MAX_WORDS constant in XenLMsri.h then recompiling will solve your issue.

Best,
Anthony
